server:
  port: 8800
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
#      table-prefix: sys_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzazz-auth?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: zzazz
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9